config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :dishes

      resources :bookmarks

      resources :venues

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "venues#index"
  resources :dishes
  resources :bookmarks
  resources :venues
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
require "open-uri"
class Venue < ApplicationRecord
  before_validation :geocode_map_address

  def geocode_map_address
    if map_address.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(map_address)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.map_address_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.map_address_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.map_address_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  # Direct associations

  has_many   :bookmarks,
             dependent: :destroy

  has_many   :dishes,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/venues_controller.rb
class Api::V1::VenuesController < Api::V1::GraphitiController
  def index
    venues = VenueResource.all(params)
    respond_with(venues)
  end

  def show
    venue = VenueResource.find(params)
    respond_with(venue)
  end

  def create
    venue = VenueResource.build(params)

    if venue.save
      render jsonapi: venue, status: :created
    else
      render jsonapi_errors: venue
    end
  end

  def update
    venue = VenueResource.find(params)

    if venue.update_attributes
      render jsonapi: venue
    else
      render jsonapi_errors: venue
    end
  end

  def destroy
    venue = VenueResource.find(params)

    if venue.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: venue
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy]

  def index
    @q = Venue.ransack(params[:q])
    @venues = @q.result(distinct: true).includes(:dishes,
                                                 :bookmarks).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@venues.where.not(map_address_latitude: nil)) do |venue, marker|
      marker.lat venue.map_address_latitude
      marker.lng venue.map_address_longitude
    end
  end

  def show
    @bookmark = Bookmark.new
    @dish = Dish.new
  end

  def new
    @venue = Venue.new
  end

  def edit; end

  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue, notice: "Venue was successfully created."
    else
      render :new
    end
  end

  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: "Venue was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_url, notice: "Venue was successfully destroyed."
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :map_address, :neighborhood, :city)
  end
end

app/views/venues/_all_photos_map.html.erb
<div id="location_map" style="height: 480px;"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/venues/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Venue #<%= venue.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= venue.name %></dd>

      <dt>Map address</dt>
      <dd>
        <div>
          <%= render partial: "venues/one_photo_map" %>
        </div>
      </dd>

      <dt>Neighborhood</dt>
      <dd><%= venue.neighborhood %></dd>

      <dt>City</dt>
      <dd><%= venue.city %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back venue, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_venue_url(venue), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to venue, method: :delete, data: { confirm: "Do you really want to delete this venue?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(venue.updated_at) %> ago
  </div>
</div>

app/views/venues/_form.html.erb
<% was_validated = venue.errors.any? %>

<%= form_with(model: venue, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = venue.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% venue.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% map_address_class = "form-control" %>
    <% map_address_was_invalid = venue.errors.include?(:map_address) %>

    <% if was_validated %>
      <% if map_address_was_invalid %>
        <% map_address_class << " is-invalid" %>
      <% else %>
        <% map_address_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :map_address %>
    <%= f.text_field :map_address, class: map_address_class, placeholder: "Enter map address" %>
    <% if map_address_was_invalid %>
      <% venue.errors.full_messages_for(:map_address).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% neighborhood_class = "form-control" %>
    <% neighborhood_was_invalid = venue.errors.include?(:neighborhood) %>

    <% if was_validated %>
      <% if neighborhood_was_invalid %>
        <% neighborhood_class << " is-invalid" %>
      <% else %>
        <% neighborhood_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :neighborhood %>
    <%= f.text_field :neighborhood, class: neighborhood_class, placeholder: "Enter neighborhood" %>
    <% if neighborhood_was_invalid %>
      <% venue.errors.full_messages_for(:neighborhood).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% city_class = "form-control" %>
    <% city_was_invalid = venue.errors.include?(:city) %>

    <% if was_validated %>
      <% if city_was_invalid %>
        <% city_class << " is-invalid" %>
      <% else %>
        <% city_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :city %>
    <%= f.text_field :city, class: city_class, placeholder: "Enter city" %>
    <% if city_was_invalid %>
      <% venue.errors.full_messages_for(:city).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/venues/_list_item.html.erb
<%= link_to venue, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= venue %>
    <small class="text-muted">
      <%= time_ago_in_words(venue.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/venues/_one_photo_map.html.erb
<div id="location_map" style="height: 480px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @venue.map_address_latitude %>,
        "lng": <%= @venue.map_address_longitude %>,
        "infowindow": "<h5><%= @venue.created_at %></h5><small><%= @venue.map_address_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/venues/_venue_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#venue_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @venue.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <% if current_user == bookmark.user %>
          <%= link_to bookmark, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="venue_bookmarks_new_form">
        <%= render partial: "venues/venue_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/venues/_venue_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.hidden_field :venue_id, value: @venue.id %>

  <div class="form-group">
    <%= f.label :dish_id %>

    <%= f.text_field :dish_id, class: "form-control" %>
  </div>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/venues/_venue_dishes.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Dishes

    <a data-toggle="collapse" href="#venue_dishes_new_form">
      Add dish
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @venue.dishes.each do |dish| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to dish, dish %>

        <%= link_to dish, method: :delete, data: { confirm: "Do you really want to delete this dish" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="venue_dishes_new_form">
        <%= render partial: "venues/venue_dishes_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/venues/_venue_dishes_new_form.html.erb
<%= form_with(model: @dish, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.hidden_field :venue_id, value: @venue.id %>

  <div class="form-group">
    <%= f.label :cuisine %>

    <%= f.text_field :cuisine, class: "form-control" %>
  </div>

  <%= f.submit "Create dish", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/venues/_venues_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "venues_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :city_cont, "City contains" %>
    <%= f.text_field :city_cont, :class => "form-control", :placeholder => "City contains" %>
  </div>

  <div class="form-group">
    <%= f.label :neighborhood_cont, "Neighborhood contains" %>
    <%= f.text_field :neighborhood_cont, :class => "form-control", :placeholder => "Neighborhood contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :dishes_name_cont, "Dishes name contains" %>
    <%= f.text_field :dishes_name_cont, :class => "form-control", :placeholder => "Dishes name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/venues" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#venues_filters">
  Show filters
</a>

app/views/venues/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Venue #<%= @venue.id %>
      </h2>

      <div class="card-body">
        <%= render "form", venue: @venue %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Venues

      <%= link_to new_venue_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "venues/venues_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "venues/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Venues

        <%= link_to new_venue_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @venues, partial: "list_item", as: :venue %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @venues, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/venues/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Venue
      </h2>

      <div class="card-body">
        <%= render "form", venue: @venue %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @venue, partial: "card", as: :venue %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "venues/venue_dishes" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "venues/venue_bookmarks" %>
  </div>
</div>